<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMDF1smQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMDF1smQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMDF1smQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMDF1smQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMDF1smQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'MDF1smQ',
    'container.build_id' => 'a309305b',
    'container.build_time' => 1589346637,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMDF1smQ');
