<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\StandwichController::home'], [], [['text', '/']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\StandwichController::contact'], [], [['text', '/contact']], [], []],
    'menu' => [[], ['_controller' => 'App\\Controller\\StandwichController::menu'], [], [['text', '/menu']], [], []],
    'connection' => [[], ['_controller' => 'App\\Controller\\StandwichController::connection'], [], [['text', '/connection']], [], []],
    'commande' => [[], ['_controller' => 'App\\Controller\\StandwichController::commande'], [], [['text', '/commande']], [], []],
    'classique' => [[], ['_controller' => 'App\\Controller\\StandwichController::classique'], [], [['text', '/menu/classique']], [], []],
    'speciaux' => [[], ['_controller' => 'App\\Controller\\StandwichController::speciaux'], [], [['text', '/menu/speciaux']], [], []],
    'burgers' => [[], ['_controller' => 'App\\Controller\\StandwichController::burgers'], [], [['text', '/menu/burgers']], [], []],
    'salades' => [[], ['_controller' => 'App\\Controller\\StandwichController::salades'], [], [['text', '/menu/salades']], [], []],
    'assiettes' => [[], ['_controller' => 'App\\Controller\\StandwichController::assiettes'], [], [['text', '/menu/assiettes']], [], []],
    'panini' => [[], ['_controller' => 'App\\Controller\\StandwichController::panini'], [], [['text', '/menu/panini']], [], []],
    'tacos' => [[], ['_controller' => 'App\\Controller\\StandwichController::tacos'], [], [['text', '/menu/tacos']], [], []],
    'barquettes' => [[], ['_controller' => 'App\\Controller\\StandwichController::barquettes'], [], [['text', '/menu/barquettes']], [], []],
    'desserts' => [[], ['_controller' => 'App\\Controller\\StandwichController::desserts'], [], [['text', '/menu/desserts']], [], []],
    'boissons' => [[], ['_controller' => 'App\\Controller\\StandwichController::boissons'], [], [['text', '/menu/boissons']], [], []],
];
